jobs:
  checking-flake:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
      with:
        fetch-depth: 1
    - uses: DeterminateSystems/nix-installer-action@v19
    - name: Magic Nix Cache(Use GitHub Actions Cache)
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Run nix flake check
      run: nix -vL flake check --impure --all-systems --no-build
    timeout-minutes: 30
'on':
  pull_request:
    branches:
    - main
    paths:
    - flake.nix
    - flake.lock
    - flake/**
  push:
    branches:
    - main
    paths:
    - flake.nix
    - flake.lock
    - flake/**
  workflow_dispatch: {}
